"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var auth_1 = require("../../core/errors/middleware/auth");
var requireRole_1 = require("../../core/errors/middleware/requireRole");
var student_controller_1 = require("./student.controller");
var router = (0, express_1.Router)();
router.post("/", student_controller_1.StudentController.create);
router.get("/", student_controller_1.StudentController.list);
router.get("/:studentUid", student_controller_1.StudentController.get);
router.patch("/:studentUid/status", student_controller_1.StudentController.updateStatus);
router.post("/:studentUid/promote", student_controller_1.StudentController.promote);
router.post("/", (0, auth_1.auth)(), (0, requireRole_1.requireRole)("SCHOOL_ADMIN"), student_controller_1.StudentController.create);
router.get("/", (0, auth_1.auth)(), (0, requireRole_1.requireRole)("SCHOOL_ADMIN", "TEACHER"), student_controller_1.StudentController.list);
router.get("/:studentUid", (0, auth_1.auth)(), (0, requireRole_1.requireRole)("SCHOOL_ADMIN", "TEACHER"), student_controller_1.StudentController.get);
router.patch("/:studentUid/status", (0, auth_1.auth)(), (0, requireRole_1.requireRole)("SCHOOL_ADMIN"), student_controller_1.StudentController.updateStatus);
router.post("/:studentUid/promote", (0, auth_1.auth)(), (0, requireRole_1.requireRole)("SCHOOL_ADMIN"), student_controller_1.StudentController.promote);
router.patch("/:studentUid/stipend-beneficiary", (0, auth_1.auth)(), (0, requireRole_1.requireRole)("SCHOOL_ADMIN"), student_controller_1.StudentController.updateStipendBeneficiary);
router.get("/:studentUid/stipend-beneficiary", (0, auth_1.auth)(), (0, requireRole_1.requireRole)("SCHOOL_ADMIN", "TEACHER"), student_controller_1.StudentController.getStipendBeneficiary);
exports.default = router;
