"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var student_routes_1 = require("./modules/student/student.routes");
var resultConfig_routes_1 = require("./modules/result-config/resultConfig.routes");
var resultSnapshot_routes_1 = require("./modules/result-snapshot/resultSnapshot.routes");
var resultSheet_routes_1 = require("./modules/result-sheet/resultSheet.routes");
var marksheet_routes_1 = require("./modules/marksheet/marksheet.routes");
var auth_routes_1 = require("./modules/auth/auth.routes");
var academicRecord_routes_1 = require("./modules/academic-record/academicRecord.routes");
var idCard_routes_1 = require("./modules/id-card/idCard.routes");
var bulk_routes_1 = require("./modules/bulk/bulk.routes");
var router = (0, express_1.Router)();
router.use("/students", student_routes_1.default);
router.use("/result-configs", resultConfig_routes_1.default);
router.use("/result-snapshots", resultSnapshot_routes_1.default);
router.use("/result-sheets", resultSheet_routes_1.default);
router.use("/marksheets", marksheet_routes_1.default);
router.use("/auth", auth_routes_1.default);
router.use("/academic-records", academicRecord_routes_1.default);
router.use("/id-cards", idCard_routes_1.default);
router.use("/bulk", bulk_routes_1.default);
exports.default = router;
